import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  //Your new manual sidebar


  k8sCoreMythsSidebar: [
    {
      type: 'autogenerated',

      dirName: "k8s-core-myths"
    },
  ],
  k8sEcosystemMythsSidebar: [
    {
      type: 'autogenerated',

      dirName: "k8s-ecosystem-myths"
    },
  ],
  k8sPlatformMythsSidebar: [
    {
      type: 'autogenerated',

      dirName: "k8s-platform-myths"
    },
  ],

  k8sDomainMythsSidebar: [
    {
      type: 'autogenerated',

      dirName: "k8s-domain-myths"
    },
  ],
};

export default sidebars;

